services:
  wgvpn:
    image: ghcr.io/wg-easy/wg-easy

    container_name: wireguardvpn

    environment:
#      PASSWORD: /run/secrets/pwd_wgvpn
      PASSWORD: $PWD_NAME
      WG_HOST: $IP_ADDRESS

    secrets:
      - pwd_wgvpn

    volumes:
      - fs_wgvpn:/etc/wireguard
      - fs_wgvpn:/lib/modules
    ports:
      - "$PORT_UDP_HST:$PORT_UDP_TGT/udp"
      - "$PORT_TCP_HST:$PORT_TCP_TGT/tcp"

    restart: unless-stopped

    cap_add:
      - NET_ADMIN
      - SYS_MODULE

    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

secrets:
  pwd_wgvpn:
    file: pwd_wgvpn.txt

volumes:
  fs_wgvpn: